### PR TITLE
Add graceful shutdown for grpc server and http server

### LINKED ISSUE #439: Graceful shutdown
Add graceful shutdown to different parts of the system:

- [x] API: gRPC server
- [x] API: HTTP gateway
- [ ] more?

### PR DESCRIPTION
**Pull request by zeina1i**
# Ticket(s)
Closes #439 

## Description
This PR adds graceful shutdown functionality to the gRPC API and its HTTP gateway.

## Related PRs
N/A

## Development Checklist

- [x] I have added a descriptive title to this PR.
- [x] I have squashed related commits together.
- [x] I have rebased my branch on top of the latest main branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added docstring(s) to my code.
- [ ] I have made corresponding changes to the documentation (docs).
- [x] I have updated docs using `make gen-docs` command.
- [ ] I have added tests for my changes.
- [x] I have signed all the commits.

## Legal Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/gatewayd-io/gatewayd/blob/main/CONTRIBUTING.md) document.
- [x] I have read and understood the [Code of Conduct](https://github.com/gatewayd-io/gatewayd/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and agreed to the [Apache CLA](https://www.apache.org/licenses/contributor-agreements.html) (required).
- [x] I have read and agreed to the [LICENSE](https://github.com/gatewayd-io/gatewayd/blob/main/LICENSE) (required).

### CODE REVIEW

**Review by mostafa — COMMENTED** [review]
Hey @zeina1i,

Thanks for your contribution! 🙏  LGTM, although there are linter errors, yet what do you think about this proposal?

We can have structs and interfaces, just like the plugin registry and other ones, and store the variables inside those structs, while the interface defines the start and stop functions. Something like this:

```go
type IAPIServer interface {
    Start()
    Shutdown()
}

type GRPCServer struct {
    api *...
    grpcServer *...
    listener *...
}

type HTTPGateway struct {
    ...
}
```

And then have `New*` functions to create instances of those structs.

**Comment by zeina1i** [comment]
Hey @mostafa 
Welcome.
I would fix the lint errors🙏

That's a great enhancements. I would make it happen asap.

**Comment by zeina1i** [comment]
Hey @mostafa 

ready for another review :)

**Review by mostafa — APPROVED** [review]
Hey @zeina1i,

Thank you for your contribution! :pray: I'll fix the linter issues and will merge it ASAP.

**Comment by zeina1i** [comment]
Welcome @mostafa 
Thanks

**Pull request merged**
